openapi: 3.0.0
info:
  title: User Login API
  description: PNC SpringBoot-Swagger Assignment.
  summary: This application uses Spring boot and Swagger and demos login with criteria

contact:
  name: Maninderjeet Singh
  email: maninderjeet.singh@example.com

license:
  name: "License No - N/A"

version: v1.0.0

servers:
  - description: Dev
    url: http://localhost:8080

  - description: Test
    url: http://localhost:8080

paths:
  /users/login/username/{username}/password/{password}/ipaddress/{ipaddress}:
    get:
      summary: Logins by username, password and specific geo-location
      parameters:
        - name: username
          in: path
          description: 'The username of the user to return.'
          required: true
          schema:
            type: string
        - name: password
          in: path
          required: true
          description:
            >
            
            Password must have 

             1.at least 8 characters long, 
            
             2.contains at least 1 Capitalized letter
            
             3.contains at least 1 number  
            
             4.contains at least one of the following: _ # $ %

          schema:
            type: string
            minimum: 8
            pattern: "^(?=.*[A-Z])(?=.*[0-9])(?=.*[_#$%])[A-Za-z0-9_#$%]{8}$"
            description: "Password must have at least 8 characters long, contains at least 1 Capitalized letter, 1 number and one of the following special characters: _ # $ %"
        - name: ipaddress
          in: path
          required: true
          description: The ipaddress of the user to return.
          schema:
            type: string
      responses:
        '200':
          description: A message.
          content:
            text/plain:
              schema:
                type: string
              example:
                >
                ID: xxxxxxxx-xxxx..
                 Welcome user from Montreal
        '400':
          description: Any specified value is invalid.
        '404':
          description: The User with specified credentials is not found.
        '500':
          description: Encountered some error.
        default:
          description: Unexpected error.


components:
  schemas:
    User:
      required:
        - username
        - password
        - ipaddress
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 4
        username:
          type: string
          minimum: 1
          example: user1
        password:
          type: string
          example: Abc_1234
        ipaddress:
          type: string
          minimum: 1
          example: 123.456.789.000
